Mama-Burger/Areas/User/Controllers/SiparisController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using MamaBurger.DTOsVMs.DTOs;
using MamaBurger.Classes.Entites;
using MamaBurger.Classes.Enums;
using System.Security.Claims;
using MamaBurger.Data;
using Microsoft.EntityFrameworkCore;

namespace MamaBurger.Areas.User.Controllers
{
    [Area("User")]
    [Authorize(Roles = "Musteri,Admin")]
    public class SiparisController : Controller
    {
        ApplicationDbContext _service;
        SiparisOlusturDTO siparisOlusturDTO;
        private readonly UserManager<AppUser> userManager;

        public SiparisController(ApplicationDbContext service, UserManager<AppUser> _userManager)

        {
            _service = service;
            userManager = _userManager;

            siparisOlusturDTO = new();
            siparisOlusturDTO.Menuler = _service.Menuler.Where(x => x.AktifMi == true).ToList();
            siparisOlusturDTO.ExtraMalzemeler = _service.ExtraMalzemeler.ToList();
            this.userManager = _userManager;
        }

        public IActionResult SiparisOlustur()
        {
            return View(siparisOlusturDTO);
        }

        [HttpPost]
        public IActionResult SiparisGonder(SiparisGonderDTO siparisGonderDTO)
        {
            Menu menu = _service.Menuler.Find(siparisGonderDTO.MenuID);

            //Menu menu = _service.Menuler.Where(m => m.MenuID == siparisGonderDTO.MenuID).SingleOrDefault();
            //if (menu == null)
            //{

            //    throw new Exception("Menü bulunamadı.");
            //}

            siparisGonderDTO.MenuAdi = menu.Adi;
            siparisGonderDTO.Fiyat = menu.Fiyat;
            if (siparisGonderDTO.Boyut == Boyut.Büyük) siparisGonderDTO.Fiyat *= 1.4M;
            else if (siparisGonderDTO.Boyut == Boyut.Orta) siparisGonderDTO.Fiyat *= 1.2M;
            siparisGonderDTO.Fiyat *= siparisGonderDTO.Adet;
            Sepet sepet = new Sepet()
            {
                MenuID = siparisGonderDTO.MenuID,
                Adet = siparisGonderDTO.Adet,
                Boyut = siparisGonderDTO.Boyut,
                //Fiyat = siparisGonderDTO.Fiyat,
                UserID = siparisGonderDTO.UserID,
                AktifMi = true
            };

            _service.Sepettekiler.Add(sepet);
            _service.SaveChanges();

            siparisGonderDTO.Sepettekiler = _service.Sepettekiler.Where(x => x.UserID == siparisGonderDTO.UserID).Include(x => x.Menu).ToList();

            if (siparisGonderDTO.Sepettekiler.Count > 1 && siparisGonderDTO.ekleme == 1)
            {

                return PartialView("_SepetTemizlensinMi", siparisGonderDTO);
            }

            return PartialView("_SiparisListesi", siparisGonderDTO);
        }




        public IActionResult SepetiOnayla(int id)
        {
            SepetiOnaylaDTO sepetiOnaylaDTO = new()
            {
                Sepettekiler = _service.Sepettekiler.Where(x => x.UserID == id).ToList()
            };
            return View(sepetiOnaylaDTO);
        }

        public IActionResult SiparisOnayla(int id)
        {
            Siparis siparis = new()
            {
                UserID = id
            };

            _service.Siparisler.Add(siparis);
            _service.SaveChanges();

            List<Sepet> sepetIcerigi = _service.Sepettekiler.Where(x => x.UserID == id).ToList();
            foreach (Sepet item in sepetIcerigi)
            {
                if (item.MenuID != null)
                {
                    SiparislerMenuler siparislerMenu = new SiparislerMenuler()
                    {
                        SiparisID = siparis.ID,
                        MenuID = (int)item.MenuID,
                        Boyut = item.Boyut,
                        Adet = item.Adet,
                        TotalFiyat = item.Fiyat
                    };
                    _service.SiparislerMenuler.Add(siparislerMenu);
                    _service.Sepettekiler.Remove(item);
                    _service.SaveChanges();
                }
            }


            return RedirectToAction("SiparisOlustur");
        }
        [HttpPost]
        public IActionResult SepettenSil(SepettenSilDTO sepettenSilDTO)
        {
            Sepet sepet = _service.Sepettekiler.Where(x => x.ID == sepettenSilDTO.sepetID).SingleOrDefault();
            if (sepet.Adet > 1)
            {
                sepet.Fiyat = (sepet.Fiyat / sepet.Adet) * (sepet.Adet - 1);
                sepet.Adet--;
                _service.Sepettekiler.Update(sepet);
                _service.SaveChanges();
            }
            else
            {
                _service.Sepettekiler.Remove(sepet);
                _service.SaveChanges();

            }
            SiparisGonderDTO siparisGonderDTO = new();
            siparisGonderDTO.Sepettekiler = _service.Sepettekiler.Where(x => x.AktifMi == true).ToList();

            return PartialView("_SiparisListesi", siparisGonderDTO);
        }
        [HttpPost]
        public IActionResult AdetArttır(SepettenSilDTO sepettenSilDTO)
        {
            Sepet sepet = _service.Sepettekiler.Where(x => x.ID == sepettenSilDTO.sepetID).SingleOrDefault();
            sepet.Fiyat = (sepet.Fiyat / sepet.Adet) * (sepet.Adet + 1);
            sepet.Adet++;
            _service.Sepettekiler.Update(sepet);
            _service.SaveChanges();
            SiparisGonderDTO siparisGonderDTO = new();
            siparisGonderDTO.Sepettekiler = _service.Sepettekiler.Where(x => x.AktifMi == true).ToList();
            return PartialView("_SiparisListesi", siparisGonderDTO);
        }
        public IActionResult Siparis()
        {
            var userIDClaim = HttpContext.User.FindFirst(ClaimTypes.NameIdentifier);

            int userID = int.Parse(userIDClaim.Value);

            List<Siparis> siparis = _service.Siparisler.Where(x => x.UserID == userID).Include(x => x.SiparislerMenuler).ToList();

            return View(siparis);
        }

        [HttpPost]
        public IActionResult SepetTemizle(SepetTemizleDTO sepetTemizleDTO)
        {
            int sonEklenenId = _service.Sepettekiler.Max(x => x.ID);
            foreach (Sepet item in _service.Sepettekiler.Where(x => x.UserID == sepetTemizleDTO.userId && x.ID != sonEklenenId).ToList())
            {
                _service.Sepettekiler.Remove(item);
                _service.SaveChanges();
            }
            SiparisGonderDTO siparisGonderDTO = new()
            {
                Sepettekiler = _service.Sepettekiler.Where(x => x.UserID == sepetTemizleDTO.userId).Include(x => x.Menu).ToList()
            };
            return PartialView("_SiparisListesi", siparisGonderDTO);
        }
        [HttpPost]
        public IActionResult SepetYukle(SepetTemizleDTO sepetTemizleDTO)
        {
            SiparisGonderDTO siparisGonderDTO = new()
            {
                Sepettekiler = _service.Sepettekiler.Where(x => x.UserID == sepetTemizleDTO.userId).ToList()
            };
            return PartialView("_SiparisListesi", siparisGonderDTO);
        }


        public IActionResult _SiparisListesi(int userId)
        {
            // Kullanıcının sepetindeki ürünleri al
            var sepetUrunleri = _service.Sepettekiler.Where(x => x.UserID == userId).Include(x => x.Menu).ToList();

            // SiparisGonderDTO nesnesi oluştur
            var siparisGonderDTO = new SiparisGonderDTO
            {
                Sepettekiler = sepetUrunleri
            };

            return PartialView("_SiparisListesi", siparisGonderDTO);
        }

        [HttpPost]
        public IActionResult _SiparisListesi(SiparisGonderDTO siparisGonderDTO)
        {
            // SiparisGonderDTO içindeki userId'yi kullanarak kullanıcının sepetini güncelle
            var sepetUrunleri = _service.Sepettekiler.Where(x => x.UserID == siparisGonderDTO.UserID).Include(x => x.Menu).ToList();
            siparisGonderDTO.Sepettekiler = sepetUrunleri;

            return PartialView("_SiparisListesi", siparisGonderDTO);
        }

        [HttpPost]
        public IActionResult SepeteEkle(int urunId, int adet, int boyut)
        {
            // Ürünü sepete eklemek için gerekli verileri toplayın

            // Veritabanından ürün bilgisini alın (örneğin, urunId kullanılarak)

            // Ürünü sepete ekleyin
            Sepet sepetItem = new Sepet
            {
                UrunID = urunId,
                Adet = adet,
                Boyut =(Boyut)boyut,
                // Diğer gerekli bilgileri de ekleyin
            };

            //_service.Sepet.Add(sepetItem);
            _service.SaveChanges();

            // Sepete eklendikten sonra kullanıcıyı uygun bir sayfaya yönlendirin
            return RedirectToAction("SiparisOlustur");
        }


    }
}

Mama-Burger/Areas/User/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MamaBurger</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/MamaBurger.styles.css" asp-append-version="true" />
    @* <link href="~/css/style.css" rel="stylesheet" /> *@


    <!-- Favicon -->
    <link href="img/favicon.ico" rel="icon">

    <!-- Google Web Fonts -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Heebo:wght@400;500;600&family=Nunito:wght@600;700;800&family=Pacifico&display=swap" rel="stylesheet">

    <!-- Icon Font Stylesheet -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.0/css/all.min.css" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.1/font/bootstrap-icons.css" rel="stylesheet">

    <!-- Libraries Stylesheet -->
    <link href="~/template2/lib/animate/animate.min.css" rel="stylesheet">
    <link href="~/template2/lib/owlcarousel/assets/owl.carousel.min.css" rel="stylesheet">
    <link href="~/template2/lib/tempusdominus/css/tempusdominus-bootstrap-4.min.css" rel="stylesheet" />

    <!-- Customized Bootstrap Stylesheet -->
    <link href="~/template2/css/bootstrap.min.css" rel="stylesheet">

    <!-- Template Stylesheet -->
    <link href="~/template2/css/style.css" rel="stylesheet">

</head>
<body>
    

    <!-- Navbar & Hero Start -->
    <header>
        <div class="container-xxl position-relative p-0">
            <nav class="navbar navbar-expand-lg navbar-dark bg-dark px-4 px-lg-5 py-3 py-lg-0">
                <a asp-area ="" asp-controller="Home" asp-action="Index" class="navbar-brand p-0">
                    <h1 class="text-primary m-0"><i class="fa fa-hamburger me-3"></i>Mama Burger</h1>
                    <!-- <img src="img/logo.png" alt="Logo"> -->
                </a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse">
                    <span class="fa fa-bars"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarCollapse">
                    <div class="navbar-nav ms-auto py-0 pe-4">
                        <a class="nav-item nav-link active" asp-area="" asp-controller="Home" asp-action="Index">Anasayfa</a>
                        @* <a class="nav-item nav-link" asp-controller="Home" asp-action="Privacy">Privacy</a> *@
                        <a asp-area="" asp-action="ContactUs" asp-controller="Home" class="nav-item nav-link">İletişim</a>
                        <partial name="_LoginPartial" />
                        @* <a href="service.html" class="nav-item nav-link">Service</a>
                        <a href="menu.html" class="nav-item nav-link">Menu</a> *@
                        @* <div class="nav-item dropdown">
                            <a href="#" class="nav-link dropdown-toggle" data-bs-toggle="dropdown">Pages</a>
                            <div class="dropdown-menu m-0">
                                <a href="booking.html" class="dropdown-item">Booking</a>
                                <a href="team.html" class="dropdown-item">Our Team</a>
                                <a href="testimonial.html" class="dropdown-item">Testimonial</a>
                            </div>
                        </div> *@
                        
                    </div>
                    <a asp-area="User" asp-controller="Siparis" asp-action="SiparisOlustur" class="btn btn-primary py-2 px-4">Sipariş Ver</a>

                </div>
            </nav>
        </div>
    </header>

    <!-- Navbar & Hero End -->
    @*    <!-- Spinner Start -->
    <div id="spinner" class="show bg-white position-fixed translate-middle w-100 vh-100 top-50 start-50 d-flex align-items-center justify-content-center">
    <div class="spinner-border text-primary" style="width: 3rem; height: 3rem;" role="status">
    <span class="sr-only">Loading...</span>
    </div>
    </div>
    <!-- Spinner End --> *@

    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>
    <!-- Footer Start -->
  @*   <footer> *@
    @* <footer class="footer bg-footer-custom">
    <div class="container-fluid bg-dark text-light footer pt-5 mt-5 wow fadeIn" data-wow-delay="0.1s">
        <div class="container py-5">
            <div class="row g-5">
                <div class="col-lg-3 col-md-6">
                    <h4 class="section-title ff-secondary text-start text-primary fw-normal mb-4">Şirketimiz</h4>
                        <a class="btn btn-link" asp-controller="Home" asp-action="Index">Hakkımızda</a>
                        <a class="btn btn-link" asp-action="ContactUs" asp-controller="Home">Bize Ulaşın</a> *@
                    @* <a class="btn btn-link" href="">Reservation</a>
                    <a class="btn btn-link" href="">Privacy Policy</a>
                    <a class="btn btn-link" href="">Terms & Condition</a> *@
                @* </div>
                <div class="col-lg-3 col-md-6">
                    <h4 class="section-title ff-secondary text-start text-primary fw-normal mb-4">Bize Ulaşın</h4>
                        <p class="mb-2"><i class="fa fa-map-marker-alt me-3"></i>Rasimpaşa, 34716 Kadıköy/İstanbul</p>
                        <p class="mb-2"><i class="fa fa-phone-alt me-3"></i>uuu1j33³ğ6akhı6000000ikimilyar</p>
                    <p class="mb-2"><i class="fa fa-envelope me-3"></i>burgermama@gmail.com</p> *@
                   @*  <div class="d-flex pt-2">
                        <a class="btn btn-outline-light btn-social" href=""><i class="fab fa-twitter"></i></a>
                        <a class="btn btn-outline-light btn-social" href=""><i class="fab fa-facebook-f"></i></a>
                        <a class="btn btn-outline-light btn-social" href=""><i class="fab fa-youtube"></i></a>
                        <a class="btn btn-outline-light btn-social" href=""><i class="fab fa-linkedin-in"></i></a>
                    </div> *@
               @*  </div>
                <div class="col-lg-3 col-md-6">
                    <h4 class="section-title ff-secondary text-start text-primary fw-normal mb-4">Çalışma Saatleri</h4>
                    <h5 class="text-light fw-normal">Haftaiçi</h5>
                    <p>12.00-23.00</p>
                    <h5 class="text-light fw-normal">Haftasonu</h5>
                    <p>13.00 - 02.00</p>
                </div>
              
            </div>
        </div>
        <div class="container">
            <div class="copyright">
                <div class="row">
                    <div class="col-md-6 text-center text-md-start mb-3 mb-md-0">
                        &copy; <a class="border-bottom" href="#">Mama Burger</a>, All Right Reserved.
                    </div>
                    <div class="col-md-6 text-center text-md-end">
                        <div class="footer-menu">
                                <a asp-controller="Home" asp-action="Index">Anasayfa</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    </footer> *@

    <!-- Footer End -->
    <!-- Back to Top -->
    <a href="#" class="btn btn-lg btn-primary btn-lg-square back-to-top"><i class="bi bi-arrow-up"></i></a>
    



    <!-- JavaScript Libraries -->
    <script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/template2/lib/wow/wow.min.js"></script>
    <script src="~/template2/lib/easing/easing.min.js"></script>
    <script src="~/template2/lib/waypoints/waypoints.min.js"></script>
    <script src="~/template2/lib/counterup/counterup.min.js"></script>
    <script src="~/template2/lib/owlcarousel/owl.carousel.min.js"></script>
    <script src="~/template2/lib/tempusdominus/js/moment.min.js"></script>
    <script src="~/template2/lib/tempusdominus/js/moment-timezone.min.js"></script>
    <script src="~/template2/lib/tempusdominus/js/tempusdominus-bootstrap-4.min.js"></script>
	<script src="~/js/site.js"></script>
    <!-- Template Javascript -->
    <script src="~/template2/js/main.js"></script>
    <script src="~/js/sepet.js"></script>
    
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>