Mama-Burger/Areas/Admin/Controllers/DashboardController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Data;

namespace MamaBurger.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = "Admin")]
    public class DashboardController : Controller
    {
        
        public IActionResult Index()
        {
            return View();
        }
    }
}

Mama-Burger/Areas/Admin/Controllers/MenuController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using MamaBurger.DTOsVMs.DTOs;
using MamaBurger.Validations.MenuValidate;
using MamaBurger.Classes.Entites;
using MamaBurger.Data;

namespace MamaBurger.Areas.Admin.Controllers
{
    [Area("Admin")]
    //[Authorize(Roles = "Admin")]
    public class MenuController : Controller
    {
        ApplicationDbContext _service;

        public MenuController(ApplicationDbContext service)
        {
            _service = service;
        }

        [HttpGet]
        public IActionResult Index()
        {
            return View(_service.Menuler.ToList());
        }

        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Create(CreateMenuDTO createMenu)
        {
            CreateMenuDTOValidator validator = new();
            var valid = validator.Validate(createMenu);
            if (valid.IsValid)
            {
                Menu menu = new Menu();
                menu.Adi = createMenu.Adi;
                menu.Fiyat = createMenu.Fiyat;
                menu.AktifMi = true;
                menu.OlusturmaZamani = DateTime.Now;

                if (createMenu.Image != null && IsImage(createMenu.Image.ContentType))
                {
                    Guid guid = Guid.NewGuid();
                    string dosyaAdi = guid.ToString();
                    dosyaAdi += createMenu.Image.FileName;
                    string dosyaYolu = "wwwroot/MenuResimleri/";
                    menu.Fotograf = dosyaAdi;

                    FileStream fs = new FileStream(dosyaYolu + dosyaAdi, FileMode.Create);
                    createMenu.Image.CopyTo(fs);
                    fs.Close();
                }

                _service.Menuler.Add(menu);
                _service.SaveChanges();
                return RedirectToAction("Index");
            }
            else
            {
                foreach (var item in valid.Errors)
                {
                    ModelState.AddModelError("MenuHata", item.ErrorMessage);

                }
                return View();
            }

        }

        public IActionResult Edit(int id)
        {
            Menu updateMenu = _service.Menuler.Find(id);

            UpdateMenuDTO updateMenuDTO = new UpdateMenuDTO()
            {
                Adi = updateMenu.Adi,
                Fiyat = updateMenu.Fiyat
            };

            return View(updateMenuDTO);
        }

        [HttpPost]
        public IActionResult Edit(UpdateMenuDTO updatedMenuDto)
        {
            CreateMenuDTOValidator validator = new();
            var valid = validator.Validate(updatedMenuDto);
            if (valid.IsValid)
            {
                Menu updateMenu = _service.Menuler.Find(updatedMenuDto.ID);
                updateMenu.Adi= updatedMenuDto.Adi;
                updateMenu.Fiyat= updatedMenuDto.Fiyat;

                if (updatedMenuDto.Image != null && IsImage(updatedMenuDto.Image.ContentType))
                {
                    Guid guid = Guid.NewGuid();
                    string dosyaAdi = guid.ToString();
                    dosyaAdi += updatedMenuDto.Image.FileName;
                    string dosyaYolu = "wwwroot/MenuResimleri/";
                    updateMenu.Fotograf = dosyaAdi;

                    FileStream fs = new FileStream(dosyaYolu + dosyaAdi, FileMode.Create);
                    updatedMenuDto.Image.CopyTo(fs);
                    fs.Close();
                }

                _service.Menuler.Update(updateMenu);
                _service.SaveChanges();
                return RedirectToAction("Index");
            }
            else
            {
                foreach (var item in valid.Errors)
                {
                    ModelState.AddModelError("MenuHata", item.ErrorMessage);
                }
                return View();
            }


        }
        public IActionResult Delete(int id)
        {
            Menu deleteMenu = _service.Menuler.Find(id);
            return View(deleteMenu);
        }
        [HttpPost]
        public IActionResult Delete(Menu menu)
        {
            Menu deleteMenu = _service.Menuler.Find(menu.ID);
            deleteMenu.AktifMi = false;
            _service.Menuler.Update(deleteMenu);
            _service.SaveChanges();
            return RedirectToAction("Index");
        }

        private bool IsImage(string contentType)
        {
            string[] allowedContentTypes = { "image/jpeg", "image/png", "image/gif" };
            return allowedContentTypes.Contains(contentType);
        }
    }
}

Mama-Burger/Areas/Admin/Controllers/ProfileController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using MamaBurger.DTOsVMs.DTOs;
using MamaBurger.Validations;
using MamaBurger.Classes.Entites;
using System.Security.Claims;
using MamaBurger.Data;

namespace MamaBurger.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = "Admin")]
    public class ProfileController : Controller
    {
        ApplicationDbContext _service;

        public ProfileController(ApplicationDbContext service)
        {
            _service = service;

        }
        public IActionResult Index()
        {
            return View();
        }

        public async Task<IActionResult> Settings()
        {
            var admin=_service.Users.Where(x=>x.UserName == "cevdet@deneme.com").FirstOrDefault();

            UpdateUserDTO updateUserDTO = new UpdateUserDTO()
            {
                Ad=admin.UserName,
                Email=admin.Email,
                PhoneNumber=admin.PhoneNumber           
            };

            return View(updateUserDTO);
        }

        [HttpPost]
        public async Task<IActionResult> Settings(UpdateUserDTO updateUserDTO)
        {
            UpdateUserDTOValidator validationRules = new UpdateUserDTOValidator();
            var valid = validationRules.Validate(updateUserDTO);
            if (!valid.IsValid)
            {
                var admin = _service.Users.Where(x => x.UserName == "cevdet@deneme.com").FirstOrDefault();

                admin.Email= updateUserDTO.Email;
                admin.PhoneNumber= updateUserDTO.PhoneNumber;
                _service.Users.Update(admin);

                return RedirectToAction("Settings");
            }

            foreach (var item in valid.Errors)
            {
                ModelState.AddModelError("Hata", item.ErrorMessage);
            }
            return View();
        }
    }
}

Mama-Burger/Areas/Admin/Views/Shared/PartialViews/_FooterPartialView.cshtml
<footer class="sticky-footer bg-white">
    <div class="container my-auto">
        <div class="copyright text-center my-auto">
            <span>Copyright &copy; MAKA 2023</span>
        </div>
    </div>
</footer>

Mama-Burger/Areas/Admin/Views/Shared/PartialViews/_NavbarPartialView.cshtml
@using Microsoft.AspNetCore.Identity;
@using MamaBurger.Classes.Entites;
@inject UserManager<AppUser> UserManager
<nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">

    <!-- Sidebar Toggle (Topbar) -->
    <button id="sidebarToggleTop" class="btn btn-link d-md-none rounded-circle mr-3">
        <i class="fa fa-bars"></i>
    </button>


    <!-- Topbar Navbar -->
    <ul class="navbar-nav ml-auto">

        <!-- Nav Item - Search Dropdown (Visible Only XS) -->
        <li class="nav-item dropdown no-arrow d-sm-none">
            <a class="nav-link dropdown-toggle" href="#" id="searchDropdown" role="button"
               data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <i class="fas fa-search fa-fw"></i>
            </a>
            <!-- Dropdown - Messages -->
            <div class="dropdown-menu dropdown-menu-right p-3 shadow animated--grow-in"
                 aria-labelledby="searchDropdown">
                <form class="form-inline mr-auto w-100 navbar-search">
                    <div class="input-group">
                        <input type="text" class="form-control bg-light border-0 small"
                               placeholder="Search for..." aria-label="Search"
                               aria-describedby="basic-addon2">
                        <div class="input-group-append">
                            <button class="btn btn-primary" type="button">
                                <i class="fas fa-search fa-sm"></i>
                            </button>
                        </div>
                    </div>
                </form>
            </div>
        </li>

        <!-- Nav Item - User Information -->
        <li class="nav-item dropdown no-arrow">
            <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button"
               data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
               @{
                    AppUser user = await UserManager.GetUserAsync(User);
               }
                <span class="mr-2 d-none d-lg-inline text-gray-600 small">@user.Ad @user.Soyad</span>
                <img class="img-profile rounded-circle"
                     src="~/template/img/undraw_profile.svg">
            </a>
            <!-- Dropdown - User Information -->
            <div class="dropdown-menu dropdown-menu-right shadow animated--grow-in"
                 aria-labelledby="userDropdown">
                <a class="dropdown-item" asp-area="Admin" asp-action="Index" asp-controller="Profile">
                    <i class="fas fa-user fa-sm fa-fw mr-2 text-gray-400"></i>
                    Profil
                </a>
                <a class="dropdown-item" asp-area="Admin" asp-action="Settings" asp-controller="Profile">
                    <i class="fas fa-cogs fa-sm fa-fw mr-2 text-gray-400"></i>
                    Ayarlar
                </a>
                <div class="dropdown-divider"></div>
                <a class="dropdown-item" asp-area="" asp-action="Logout" asp-controller="User" >
                    <i class="fas fa-sign-out-alt fa-sm fa-fw mr-2 text-gray-400"></i>
                    Çıkış Yap
                </a>
            </div>
        </li>

    </ul>

</nav>

Mama-Burger/Areas/Admin/Views/Shared/PartialViews/_SidebarPartialView.cshtml
<ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">

    <!-- Sidebar - Brand -->
    <a class="sidebar-brand d-flex align-items-center justify-content-center" href="index.html">
        <div class="sidebar-brand-icon rotate-n-15">
            <i class="fas fa-laugh-wink"></i>
        </div>
        <div class="sidebar-brand-text mx-3">Admin Panel</div>
    </a>

    <!-- Divider -->
    <hr class="sidebar-divider my-0">

    <!-- Nav Item - Dashboard -->
    <li class="nav-item active">
        <a class="nav-link" asp-area="Admin" asp-action="Index" asp-controller="Dashboard">
            <i class="fas fa-fw fa-tachometer-alt"></i>
            <span>Dashboard</span>
        </a>
    </li>

    <!-- Divider -->
    <hr class="sidebar-divider" />

    <!-- Nav Item - Pages Collapse Menu -->
    <li class="nav-item">
        <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseTwo"
           aria-expanded="true" aria-controls="collapseTwo">
            <i class="fas fa-fw fa-cog"></i>
            <span>Menü İşlemleri</span>
        </a>
        <div id="collapseTwo" class="collapse" aria-labelledby="headingTwo" data-parent="#accordionSidebar">
            <div class="bg-white py-2 collapse-inner rounded">
                <a asp-area="Admin" asp-controller="Menu" asp-action="Index" class="collapse-item">Menü Listele</a>
                <a asp-area="Admin" asp-controller="Menu" asp-action="Create" class="collapse-item">Menü Ekle</a>
                <a asp-area="Admin" asp-controller="Menu" asp-action="Edit" class="collapse-item">Menü Güncelle</a>
                <a asp-area="Admin" asp-controller="Menu" asp-action="Delete" class="collapse-item">Menü Sil</a>
            </div>
        </div>
    </li>
    <li class="nav-item">
        <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseUtilities"
           aria-expanded="true" aria-controls="collapseUtilities">
            <i class="fas fa-fw fa-wrench"></i>
            <span>Extra Malzeme İşlemleri</span>
        </a>
        <div id="collapseUtilities" class="collapse" aria-labelledby="headingUtilities"
             data-parent="#accordionSidebar">
            <div class="bg-white py-2 collapse-inner rounded">
                <a asp-area="Admin" asp-controller="ExtraMalzeme" asp-action="Index" class="collapse-item">Extra Malzeme Listele</a>
                <a asp-area="Admin" asp-controller="ExtraMalzeme" asp-action="Create" class="collapse-item">Extra Malzeme Ekle</a>
                <a asp-area="Admin" asp-controller="ExtraMalzeme" asp-action="Edit" class="collapse-item">Extra Malzeme Güncelle</a>
            </div>
        </div>
    </li>

    <!-- Divider -->
    <hr class="sidebar-divider d-none d-md-block">

    <!-- Sidebar Toggler (Sidebar) -->
    <div class="text-center d-none d-md-inline">
        <button class="rounded-circle border-0" id="sidebarToggle"></button>
    </div>

</ul>